apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-serving
  namespace: mlflow
  labels:
    app: mlflow-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-serving
  template:
    metadata:
      labels:
        app: mlflow-serving
    spec:
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: mlflow-serving
          image: iad.ocir.io/<namespace>/mlflow-serving:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlflow.svc.cluster.local"
            - name: MLFLOW_MODEL_NAME
              value: "iris-logreg-model"
            - name: MLFLOW_MODEL_STAGE
              value: "Production"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-object-storage
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-object-storage
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: mlflow-object-storage
                  key: AWS_DEFAULT_REGION
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: mlflow-object-storage
                  key: MLFLOW_S3_ENDPOINT_URL
